table f_manipulados
	lineageTag: 4bc535e4-ddbd-4f41-8342-d3e465a1b224

	column uf
		dataType: string
		lineageTag: da960cad-7e58-4cca-9fce-fca8c51bcd37
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column municipio
		dataType: string
		lineageTag: 37d8dc8e-1063-43f3-a49f-fb266578002e
		summarizeBy: none
		sourceColumn: municipio

		annotation SummarizationSetBy = Automatic

	column principio_ativo
		dataType: string
		lineageTag: 9b2db8fc-6e66-4629-97ea-706b8cc35020
		summarizeBy: none
		sourceColumn: principio_ativo

		annotation SummarizationSetBy = Automatic

	column qt_ativo_por_unidade_farmacotec
		dataType: double
		lineageTag: 33f530d4-c95e-4e34-a791-ed69ea04c375
		summarizeBy: sum
		sourceColumn: qt_ativo_por_unidade_farmacotec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_unidade_farmacotecnica
		dataType: double
		lineageTag: 7228af0f-e466-4d08-9d7a-3bc21b9bff1b
		summarizeBy: sum
		sourceColumn: qtd_unidade_farmacotecnica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column conselho_prescritor
		dataType: string
		lineageTag: 2c76f8d6-1035-44f6-894a-4e0a1d000082
		summarizeBy: none
		sourceColumn: conselho_prescritor

		annotation SummarizationSetBy = Automatic

	column cid
		dataType: string
		lineageTag: f88d9635-2e02-46b5-8616-f33373de4e0d
		summarizeBy: none
		sourceColumn: cid

		annotation SummarizationSetBy = Automatic

	column ano_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4de87e5-2ccc-4a47-901a-08782fcfc12c
		summarizeBy: none
		sourceColumn: ano_mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qnt_vendida
		dataType: double
		lineageTag: b0a38532-38b4-412e-961c-ebbf3f91f099
		summarizeBy: sum
		sourceColumn: qnt_vendida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition f_manipulados = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("187.127.11.180:5434", "concurso_saude_db"),
				    public_manipulados = Fonte{[Schema="public",Item="manipulados"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_manipulados,{{"ano_mes", type date}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"filename", "qtd_registros"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Removidas", "qnt_vendida", each [qt_ativo_por_unidade_farmacotec]*[qtd_unidade_farmacotecnica]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"qnt_vendida", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

