table f_manipulados
	lineageTag: 4bc535e4-ddbd-4f41-8342-d3e465a1b224

	column uf
		dataType: string
		lineageTag: da960cad-7e58-4cca-9fce-fca8c51bcd37
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column municipio
		dataType: string
		lineageTag: 37d8dc8e-1063-43f3-a49f-fb266578002e
		summarizeBy: none
		sourceColumn: municipio

		annotation SummarizationSetBy = Automatic

	column principio_ativo
		dataType: string
		lineageTag: 9b2db8fc-6e66-4629-97ea-706b8cc35020
		summarizeBy: none
		sourceColumn: principio_ativo

		annotation SummarizationSetBy = Automatic

	column qt_ativo_por_unidade_farmacotec
		dataType: double
		lineageTag: 33f530d4-c95e-4e34-a791-ed69ea04c375
		summarizeBy: sum
		sourceColumn: qt_ativo_por_unidade_farmacotec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column conselho_prescritor
		dataType: string
		lineageTag: 2c76f8d6-1035-44f6-894a-4e0a1d000082
		summarizeBy: none
		sourceColumn: conselho_prescritor

		annotation SummarizationSetBy = Automatic

	column cid
		dataType: string
		lineageTag: f88d9635-2e02-46b5-8616-f33373de4e0d
		summarizeBy: none
		sourceColumn: cid

		annotation SummarizationSetBy = Automatic

	column ano_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4de87e5-2ccc-4a47-901a-08782fcfc12c
		summarizeBy: none
		sourceColumn: ano_mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qt_vendida
		dataType: int64
		formatString: 0
		lineageTag: eaed6eac-dfef-404d-9e3a-c7069ccab913
		summarizeBy: sum
		sourceColumn: qt_vendida

		annotation SummarizationSetBy = Automatic

	column qt_unidade_farmacotecnica
		dataType: double
		lineageTag: ee9078ef-8054-477f-b306-2e4132f0c994
		summarizeBy: sum
		sourceColumn: qt_unidade_farmacotecnica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qt_ativo_vendido
		dataType: double
		lineageTag: 11f1e8b3-f1c2-44de-9e90-5e224f9f906a
		summarizeBy: sum
		sourceColumn: qt_ativo_vendido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_tipo_manipulados = 1
		formatString: 0
		lineageTag: 0753a0d1-ed7a-420d-a21c-f12fcb0e9ee9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column categoria_cid
		dataType: string
		lineageTag: 148329fe-bf2b-455b-9c77-889edce60734
		summarizeBy: none
		sourceColumn: categoria_cid

		annotation SummarizationSetBy = Automatic

	partition f_manipulados = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("187.127.11.180:5434", "concurso_saude_db"),
				    public_manipulados = Fonte{[Schema="public",Item="manipulados"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_manipulados,{{"ano_mes", type date}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "qnt_vendida", each [qt_ativo_por_unidade_farmacotec]*[qtd_unidade_farmacotecnica]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"qnt_vendida", type number}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"qnt_vendida"}),
				    #"Texto Aparado" = Table.TransformColumns(#"Colunas Removidas",{{"uf", Text.Trim, type text}, {"municipio", Text.Trim, type text}, {"principio_ativo", Text.Trim, type text}, {"conselho_prescritor", Text.Trim, type text}}),
				    #"Texto Limpo" = Table.TransformColumns(#"Texto Aparado",{{"uf", Text.Clean, type text}, {"municipio", Text.Clean, type text}, {"principio_ativo", Text.Clean, type text}, {"conselho_prescritor", Text.Clean, type text}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Texto Limpo", "qt_ativo_vendido", each [qt_ativo_por_unidade_farmacotec]*[qt_unidade_farmacotecnica]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"qt_ativo_vendido", type number}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado2", "categoria_cid", each if Text.Length([cid])=3 then [cid] else Text.Range([cid],0,3))
				in
				    #"Personalização Adicionada2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

